### ISSUE TITLE
wrong links

### ISSUE THREAD

**Issue by bluesword443** [Waddlr-ga/waddlrbeta#1]
the download buttons go to a wrong link. fix.
also. please consider a new website style, I think I saw this one before and you don't want to be bad so don't steal.

**Comment by Tony-devno01** [comment]
Hi! Im the owner of waddlr.. 
As per the download button. It is getting fixed immidiately,
As per the website. Our web developer coded our site from scratch as far as we know. As far as our community have commented nobody has mention the website being copied from another CPPS. rather they commented as it is a unique website. If you show us any kind of proof that this website style/code belongs to another CPPS. We would happily consider recoding the CPPS.

**Comment by bluesword443** [comment]
Hello,
I can't revisit it. But if I will be able to, I'll send you the link.
As for now, I reccomend you to change it.

**Comment by bluesword443** [comment]
First of all, Waddlr has stolen the button design from "Freezy 2".
As seen here - https://freezycpps.netlify.app/play

**Comment by bluesword443** [comment]
and also here https://freezycpps.netlify.app/blog

**Comment by bluesword443** [comment]
also https://starktony.netlify.app

**Comment by chriskermit** [comment]
Hello there!
I'm responsible for Waddlr's technical side. As from what I know, Waddlr's website has been coded from scratch. Freezy 2 is a project by Tony's Evergreen Studios/Chipwood Studios, but we have sent an email to them.

**Comment by bluesword443** [comment]
Waddlr is also using an identical style notification to Freezy 2.
https://waddlrgame.ml/ and https://freezycpps.netlify.app/blog

**Comment by bluesword443** [comment]
https://waddlrgame.ml/blogwriter
the button still stolen from Freezy

**Comment by Tony-devno01** [comment]
Hello Bluesword! I am the owner of all those sites INCLUDING waddlr. i own Freezy 2 and Starktony. Starktony is my official website while freezy is my other CPPS. Waddlr's Website was made first before all. And i have told our web developer about these sites andf the code behind it is a copy of waddlr's and it was permitted. i also those codes for all my site so technically waddlr did not steal from ANY sites. It's just my sites borrowing waddlr's code. thank you!

**Comment by Tony-devno01** [comment]
Oh and one more thing. Starktony is still not a public website yet.. I am surprised you got access to a private site.

**Comment by bluesword443** [comment]
Your GitHub :)

**Comment by bluesword443** [comment]
One more thing.
Please stop stealing.
Your excuses won't do anything here.
Remember I am monitoring this.
